#server.port=8001
# ?????
#spring.datasource.url=jdbc:mysql://localhost:3306/mango_db
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## MyBatis ??
#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=com.your.package.model

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mango_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
#    username: root
#    password:

server:
  port: 8001
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mango_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password:
      filters: stat, wall, log4j, config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        allow: 127.0.0.1,192.168.1.100  # 允许访问的 IP 白名单（多个 IP 用逗号分隔）
        deny: 192.168.1.101  # 拒绝访问的 IP 黑名单（优先于白名单）
      web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      wall:
          config:
            multi-statement-allow: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mango_admin.model
