server:
  port: 8002

spring:
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  application:
    name: mango_backup
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"

mango:
  backup:
    datasource:
      host: localhost
      username: root
      password:
      database: mango_db

#debug: true